# This Dockerfile provides all cli tools and dependencies for the mocogi backend.
# It will be used as a base image in the production environment
FROM eclipse-temurin:21.0.2_13-jre-jammy
ARG PANDOC_PLATFORM_SUFFIX
ARG GIT_REPO_URL
ENV GIT_REPO_URL=${GIT_REPO_URL}
RUN apt-get update && apt-get install -y \
  latexmk \
  texlive-xetex \
  texlive-lang-german \
  vim \
  wget \
  git
RUN wget https://github.com/jgm/pandoc/releases/download/3.1.2/pandoc-3.1.2-1-$PANDOC_PLATFORM_SUFFIX.deb  \
  && dpkg -i pandoc-3.1.2-1-$PANDOC_PLATFORM_SUFFIX.deb  \
  && rm pandoc-3.1.2-1-$PANDOC_PLATFORM_SUFFIX.deb